// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppNavbar from "./components/AppNavbar";
import MobileDockClient from "./components/MobileDockClient";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-200`}>
        <AppNavbar brand="WinePairing" />
        <main className="min-h-[100svh]">{children}</main>
        {/* Mobile-only dock mounted via client wrapper */}
        <MobileDockClient />
      </body>
    </html>
  );
}
